[theme]

# Used to style primary interface elements. It's the color displayed most frequently across your app's
# screens and components. Examples of widgets using this color are st.slider and st.checkbox.
primaryColor = "#D33682" # green

# Background color for the main container.
backgroundColor = "#002B36" # not sure what blue this is

# Used as the background for most widgets. Examples of widgets with this background are st.sidebar,
# st.text_input, st.date_input.
secondaryBackgroundColor =  "#586E75" # grayish check with html css color map  <-- not enough contrast

# Font color for the page.
textColor = "#FAFAFA" # grey

# Font family (serif | sans serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "sans serif"
